# Generated by Django 3.0.8 on 2020-09-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='profile_image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
