# Generated by Django 3.0.8 on 2020-09-07 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0002_myprofile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('myprofile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myprofile.MyProfile')),
            ],
        ),
    ]
