# Generated by Django 3.0.8 on 2020-09-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0004_profilephoto_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilephoto',
            name='topic',
            field=models.CharField(default=0, max_length=30, null=True),
        ),
    ]
