# Generated by Django 3.0.8 on 2020-09-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0005_auto_20200909_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myschool', models.CharField(max_length=20)),
                ('hak', models.IntegerField(default=2)),
                ('ban', models.IntegerField(default=6)),
                ('class_intimacy', models.IntegerField(default=0)),
            ],
        ),
    ]
