# Generated by Django 3.0.9 on 2020-09-17 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='writer',
        ),
    ]
