# Generated by Django 3.0.8 on 2020-09-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_forum_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='writer',
            field=models.CharField(default='', max_length=200),
        ),
    ]
