# Generated by Django 3.0.8 on 2020-09-21 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0006_myclass'),
        ('forum', '0003_forum_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writer', to='myprofile.MyProfile', verbose_name='USERNAME'),
        ),
    ]
