# Generated by Django 3.0.8 on 2020-08-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodtracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moodtracker',
            old_name='published',
            new_name='pub_date',
        ),
        migrations.AddField(
            model_name='moodtracker',
            name='pos_neg',
            field=models.IntegerField(default=0),
        ),
    ]
