# Generated by Django 3.0.8 on 2020-08-26 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodtracker', '0003_wordcloud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wordcloud',
            old_name='wc',
            new_name='wc_image',
        ),
    ]
