# Generated by Django 3.0.8 on 2020-08-27 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moodtracker', '0004_auto_20200826_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodtracker',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='USERNAME'),
        ),
        migrations.AlterField(
            model_name='wordcloud',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='USERNAME'),
        ),
        migrations.AlterField(
            model_name='wordcloud',
            name='wc_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
