# Generated by Django 3.0.8 on 2020-09-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodtracker', '0005_auto_20200827_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodtracker',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='moodtracker',
            name='pub_date_day',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='moodtracker',
            name='pub_date_month',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='moodtracker',
            name='pub_date_year',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
