# Generated by Django 3.0.8 on 2020-09-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodtracker', '0006_auto_20200903_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodtracker',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
