# Generated by Django 3.0.8 on 2020-10-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodtracker', '0007_moodtracker_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodtracker',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
