# Generated by Django 3.0.8 on 2020-10-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodtracker', '0008_moodtracker_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodtracker',
            name='anger',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='moodtracker',
            name='contempt',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='moodtracker',
            name='disgust',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='moodtracker',
            name='fear',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='moodtracker',
            name='happiness',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='moodtracker',
            name='neutral',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='moodtracker',
            name='sadness',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='moodtracker',
            name='surprise',
            field=models.FloatField(default=0),
        ),
    ]
