# Generated by Django 3.0.8 on 2020-09-12 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myprofile', '0005_auto_20200909_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intimacy', models.IntegerField(default=0)),
                ('mate1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mate1', to='myprofile.MyProfile', verbose_name='USERNAME')),
                ('mate2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mate2', to='myprofile.MyProfile', verbose_name='USERNAME')),
            ],
        ),
        migrations.CreateModel(
            name='MateTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task1', models.IntegerField(default=0)),
                ('task2', models.IntegerField(default=0)),
                ('task3', models.IntegerField(default=0)),
                ('task4', models.IntegerField(default=0)),
                ('task5', models.IntegerField(default=0)),
                ('task6', models.IntegerField(default=0)),
                ('task7', models.IntegerField(default=0)),
                ('task8', models.IntegerField(default=0)),
                ('task9', models.IntegerField(default=0)),
                ('task10', models.IntegerField(default=0)),
                ('task11', models.IntegerField(default=0)),
                ('task12', models.IntegerField(default=0)),
                ('mate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mate.Mate')),
            ],
        ),
        migrations.CreateModel(
            name='MatePhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('mate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mate.Mate')),
            ],
        ),
    ]
