# Generated by Django 3.0.8 on 2020-09-13 01:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matetask',
            name='task1',
        ),
        migrations.RemoveField(
            model_name='matetask',
            name='task10',
        ),
        migrations.RemoveField(
            model_name='matetask',
            name='task11',
        ),
        migrations.RemoveField(
            model_name='matetask',
            name='task12',
        ),
        migrations.RemoveField(
            model_name='matetask',
            name='task2',
        ),
        migrations.RemoveField(
            model_name='matetask',
            name='task3',
        ),
        migrations.RemoveField(
            model_name='matetask',
            name='task4',
        ),
        migrations.RemoveField(
            model_name='matetask',
            name='task5',
        ),
        migrations.RemoveField(
            model_name='matetask',
            name='task6',
        ),
        migrations.RemoveField(
            model_name='matetask',
            name='task7',
        ),
        migrations.RemoveField(
            model_name='matetask',
            name='task8',
        ),
        migrations.RemoveField(
            model_name='matetask',
            name='task9',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=8)),
                ('mate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mate.Mate')),
            ],
        ),
    ]
