# Generated by Django 3.0.8 on 2020-09-13 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mate', '0002_auto_20200913_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='matetask',
            name='task1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matetask',
            name='task10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matetask',
            name='task11',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matetask',
            name='task12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matetask',
            name='task2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matetask',
            name='task3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matetask',
            name='task4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matetask',
            name='task5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matetask',
            name='task6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matetask',
            name='task7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matetask',
            name='task8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matetask',
            name='task9',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
