# Generated by Django 3.0.8 on 2020-09-15 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0005_auto_20200909_2100'),
        ('mate', '0005_matemsg'),
    ]

    operations = [
        migrations.AddField(
            model_name='matemsg',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myprofile.MyProfile', verbose_name='USERNAME'),
        ),
    ]
