# Generated by Django 3.0.8 on 2020-09-15 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mate', '0006_matemsg_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='matemsg',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='작성일'),
            preserve_default=False,
        ),
    ]
