# Generated by Django 3.1.1 on 2020-09-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsel',
            name='datenum',
            field=models.IntegerField(default=1, verbose_name='상담날짜'),
            preserve_default=False,
        ),
    ]
