# Generated by Django 3.1.1 on 2020-09-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0002_counsel_datenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsel',
            name='datenum',
            field=models.CharField(max_length=10, verbose_name='상담날짜'),
        ),
    ]
