# Generated by Django 3.1.1 on 2020-09-19 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0003_auto_20200920_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counsel',
            name='datenum',
        ),
        migrations.AddField(
            model_name='counsel',
            name='detailtext',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='상담내용'),
            preserve_default=False,
        ),
    ]
