# Generated by Django 3.1.1 on 2020-09-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0004_auto_20200920_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counsel',
            name='detailtext',
        ),
    ]
