# Generated by Django 3.1.1 on 2020-09-19 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0005_remove_counsel_detailtext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counsel',
            name='username',
        ),
    ]
