# Generated by Django 3.1.1 on 2020-09-19 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0006_remove_counsel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsel',
            name='datenum',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counsel',
            name='detailtext',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counsel',
            name='timepick',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='counsel',
            name='how',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='teacher',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='counsel',
            name='who',
            field=models.CharField(max_length=10),
        ),
    ]
