# Generated by Django 3.1.1 on 2020-09-20 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0007_auto_20200920_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsel',
            name='about',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='counsel',
            name='timepick',
            field=models.CharField(max_length=20),
        ),
    ]
