# Generated by Django 3.1.2 on 2020-10-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0009_counsel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsel',
            name='username',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
