# Generated by Django 3.1.2 on 2020-10-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0010_auto_20201018_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsel',
            name='datenum',
            field=models.CharField(max_length=20),
        ),
    ]
